name: Release Please Merge
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write
  repository-projects: read

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-flag.outputs.release_created }}
    steps:
      - name: Create Release Tag
        id: tag
        uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4.1.3
        with:
          command: ${{ inputs.command }}
          release-type: ${{ inputs.release-type }} 
      - id: release-flag
        run: echo "release_created=${{ steps.tag.outputs.release_created || false }}" >> $GITHUB_OUTPUT
